---

- name: Install locales
  ansible.builtin.apt:
    pkg: locales
    state: present

- name: Generate locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locale_locales }}"
